<?php

return [
    'APP_SECRET' => null,
    'DB_HOST_DEV' => null,
    'DB_HOST_STAGING' => null,
    'DB_NAME_DEV' => null,
    'DB_NAME_STAGING' => null,
    'DB_PASSWORD_DEV_RO' => null,
    'DB_PASSWORD_DEV_RW' => null,
    'DB_PASSWORD_STAGING_RO' => null,
    'DB_PASSWORD_STAGING_RW' => null,
    'DB_PORT_DEV' => null,
    'DB_PORT_STAGING' => null,
    'DB_USER_DEV_RO' => null,
    'DB_USER_DEV_RW' => null,
    'DB_USER_STAGING_RO' => null,
    'DB_USER_STAGING_RW' => null,
    'JWT_PASSPHRASE' => null,
    'JWT_PRIVATE_KEY' => null,
    'JWT_PUBLIC_KEY' => null,
    'RMQ_HOST_DEV' => null,
    'RMQ_HOST_STAGING' => null,
    'RMQ_PASSWORD_DEV' => null,
    'RMQ_PASSWORD_STAGING' => null,
    'RMQ_PORT_DEV' => null,
    'RMQ_PORT_STAGING' => null,
    'RMQ_USER_DEV' => null,
    'RMQ_USER_STAGING' => null,
];
