FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libicu-dev \
    libzip-dev \
    libpq-dev \
    librabbitmq-dev \
    libssl-dev \
 && docker-php-ext-install \
    intl \
    pdo \
    pdo_pgsql \
    zip

# AMQP extension (IMPORTANT)
RUN pecl install amqp \
 && docker-php-ext-enable amqp

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --prefer-dist \
    --no-interaction \
    --optimize-autoloader

COPY . .

RUN mkdir -p var/cache var/log && \
    chown -R www-data:www-data var public

EXPOSE 9000

CMD ["php-fpm", "-F"]
